import 'package:extreme_store/domain/repositories/user_preference_repo.dart';

import '../di/injection_container.dart';

class IconsConstants {
  static const googleIC = 'assets/icons/ic_google.svg';
  static const appleIC = 'assets/icons/ic_apple.svg';
  static const eyeOffIC = 'assets/icons/eye-off.svg';
  static const locationIC = 'assets/icons/location.svg';
  static const arrowDownIC = 'assets/icons/arrow-down.svg';
  static const trashIC = 'assets/icons/trash.svg';
  static const addIC = "assets/icons/add-circle.svg";
  static const minusIC= "assets/icons/minus-circle.svg";
  static const arrowRightIC = "assets/icons/arrow-right.svg";
  static const arrowRightBarIC = "assets/icons/arrow_right_bar.svg";
  static const categoriesIC = "assets/icons/categories.svg";
  static const categoryIC = "assets/icons/category.svg";
  static const editIC = "assets/icons/edit.svg";
  static const homeIC = "assets/icons/home.svg";
  static const heartIC = "assets/icons/heart.svg";
  static const profileIC = "assets/icons/profile.svg";
  static const searchIC = "assets/icons/search.svg";
  static const searchPrefIC = "assets/icons/search-pref.svg";
  static const cartIC = "assets/icons/shopping-cart.svg";
  static const shareIC = "assets/icons/share.svg";
  static const logoIC = "assets/icons/logo.svg";
  static const starIC = "assets/icons/star.svg";
  static const tickCircle = "assets/icons/tick-circle.svg";
  static const holeCircleIC = "assets/icons/hole_circle.svg";
  static const pointIC = "assets/icons/point.svg";
  static const instagramIC = "assets/icons/instagram.svg";
  static const facebookIC = "assets/icons/facebook.svg";
  static const twitterIC = "assets/icons/twitter.svg";
  static const solidCircleIC = "assets/icons/solid_circle.svg";
  static const circleBorderIC = "assets/icons/circle_border.svg";
  static const closeCircleIC = "assets/icons/close-circle.svg";
  static const addUserIC = "assets/icons/user-add.svg";
  static const linkedinIc = "assets/icons/linkedin.svg";
  static const arrowUpIC = "assets/icons/arrow-up.svg";
  static const arrowDownWideIC = "assets/icons/arrow-down2.svg";
  static const arrowRightWideIC = "assets/icons/arrow-right2.svg";
  static const checkIC = "assets/icons/check.svg";
  static const bagIC = "assets/icons/bag-tick.svg";
  static const locationSolidIC = "assets/icons/location_solid.svg";
  static const userIC = "assets/icons/user.svg";
  static const notFoundResultIC = "assets/icons/Not Found illustration.svg";
  static const noAddressIC = "assets/icons/No Address illustration.svg";
  static const noConnectionIC = "assets/icons/No Connection illustartion.svg";
  static const noFavouriteIC = "assets/icons/No Favorite illustration.svg";
  static const noMessageIC = "assets/icons/No Message illustration.svg";
  static const noNotificationIC = "assets/icons/No Notification illustration.svg";
  static const notFoundPageIC = "assets/icons/404 illustration.svg";
  static const emptyCartIC = "assets/icons/Cart illustartion.svg";
  static const arrowUpSmallIC = "assets/icons/arrow_up_small.svg";
  static const placeholder = "assets/icons/placeholder.svg";
  static const saudi = "assets/icons/sa.svg";
  static const emarat = "assets/icons/ae.svg";
  static const oman = "assets/icons/om.svg";
  static const bahrain = "assets/icons/bh.svg";
  static const qatar = "assets/icons/qa.svg";
  static const kuwait = "assets/icons/kw.svg";
  static const snapchatIC = "assets/icons/snapchat.svg";
  static const tiktokIC = "assets/icons/tiktok.svg";
  static const whatsappIC = "assets/icons/whatsapp.svg";
  static const visaIcon = "assets/icons/visa_icon.svg";
  static const masterCardIcon = "assets/icons/master_card_icon.svg";
  static const knetIcon = "assets/icons/knet_icon.svg";
  static const cashOnDelivery = "assets/icons/cash-on-delivery.svg";
  static  var appLogo = sl<UserPreferenceRepo>().getAppLogo();

}
